//
// Generated file. Do not edit manually.
//

using System.ComponentModel;

namespace Alba.CsCss.Style
{
    public enum CssPseudoClass {
        Empty,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozOnlyWhitespace,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozEmptyExceptChildrenWithLocalname,
        Lang,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozBoundElement,
        Root,
        Any,
        FirstChild,
        FirstNode,
        LastChild,
        LastNode,
        OnlyChild,
        FirstOfType,
        LastOfType,
        OnlyOfType,
        NthChild,
        NthLastChild,
        NthOfType,
        NthLastOfType,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozIsHtml,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozSystemMetric,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozLocaleDir,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozLwtheme,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozLwthemeBrightText,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozLwthemeDarkText,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozWindowInactive,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozTableBorderNonzero,
        Scope,
        NotPseudo,
        Dir,
        Link,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozAnyLink,
        Visited,
        Active,
        Checked,
        Disabled,
        Enabled,
        Focus,
        Hover,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozDragOver,
        Target,
        Indeterminate,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozFullScreen,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozFullScreenAncestor,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozFocusRing,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozBroken,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozUserDisabled,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozSuppressed,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozLoading,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozTypeUnsupported,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozTypeUnsupportedPlatform,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerClickToPlay,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerPlayPreview,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerVulnerableUpdatable,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerVulnerableNoUpdate,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerDisabled,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerBlocked,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozHandlerCrashed,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozMathIncrementScriptLevel,
        Required,
        Optional,
        Valid,
        Invalid,
        InRange,
        OutOfRange,
        DefaultPseudo,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozReadOnly,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozReadWrite,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozSubmitInvalid,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozUiinvalid,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozUivalid,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozMeterOptimum,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozMeterSubOptimum,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozMeterSubSubOptimum,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        MozPlaceholder,
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Count,
        [EditorBrowsable(EditorBrowsableState.Never)]
        NotPseudoClass,
    }
}
