//
// Generated file. Do not edit manually.
//

using System.Collections.Generic;
using Alba.CsCss.Internal;

namespace Alba.CsCss.Style
{
    internal static partial class nsCSSPseudoClasses
    {
        private static readonly IDictionary<string, nsCSSPseudoClass> sPseudoClasses =
            new Dictionary<string, nsCSSPseudoClass>(ReferenceEqualityComparer<object>.Default) {
                { ":empty", nsCSSPseudoClass.empty },
                { ":-moz-only-whitespace", nsCSSPseudoClass.mozOnlyWhitespace },
                { ":-moz-empty-except-children-with-localname", nsCSSPseudoClass.mozEmptyExceptChildrenWithLocalname },
                { ":lang", nsCSSPseudoClass.lang },
                { ":-moz-bound-element", nsCSSPseudoClass.mozBoundElement },
                { ":root", nsCSSPseudoClass.root },
                { ":-moz-any", nsCSSPseudoClass.any },
                { ":first-child", nsCSSPseudoClass.firstChild },
                { ":-moz-first-node", nsCSSPseudoClass.firstNode },
                { ":last-child", nsCSSPseudoClass.lastChild },
                { ":-moz-last-node", nsCSSPseudoClass.lastNode },
                { ":only-child", nsCSSPseudoClass.onlyChild },
                { ":first-of-type", nsCSSPseudoClass.firstOfType },
                { ":last-of-type", nsCSSPseudoClass.lastOfType },
                { ":only-of-type", nsCSSPseudoClass.onlyOfType },
                { ":nth-child", nsCSSPseudoClass.nthChild },
                { ":nth-last-child", nsCSSPseudoClass.nthLastChild },
                { ":nth-of-type", nsCSSPseudoClass.nthOfType },
                { ":nth-last-of-type", nsCSSPseudoClass.nthLastOfType },
                { ":-moz-is-html", nsCSSPseudoClass.mozIsHTML },
                { ":-moz-system-metric", nsCSSPseudoClass.mozSystemMetric },
                { ":-moz-locale-dir", nsCSSPseudoClass.mozLocaleDir },
                { ":-moz-lwtheme", nsCSSPseudoClass.mozLWTheme },
                { ":-moz-lwtheme-brighttext", nsCSSPseudoClass.mozLWThemeBrightText },
                { ":-moz-lwtheme-darktext", nsCSSPseudoClass.mozLWThemeDarkText },
                { ":-moz-window-inactive", nsCSSPseudoClass.mozWindowInactive },
                { ":-moz-table-border-nonzero", nsCSSPseudoClass.mozTableBorderNonzero },
                { ":scope", nsCSSPseudoClass.scope },
                { ":not", nsCSSPseudoClass.notPseudo },
                { ":-moz-dir", nsCSSPseudoClass.dir },
                { ":link", nsCSSPseudoClass.link },
                { ":-moz-any-link", nsCSSPseudoClass.mozAnyLink },
                { ":visited", nsCSSPseudoClass.visited },
                { ":active", nsCSSPseudoClass.active },
                { ":checked", nsCSSPseudoClass.@checked },
                { ":disabled", nsCSSPseudoClass.disabled },
                { ":enabled", nsCSSPseudoClass.enabled },
                { ":focus", nsCSSPseudoClass.focus },
                { ":hover", nsCSSPseudoClass.hover },
                { ":-moz-drag-over", nsCSSPseudoClass.mozDragOver },
                { ":target", nsCSSPseudoClass.target },
                { ":indeterminate", nsCSSPseudoClass.indeterminate },
                { ":-moz-full-screen", nsCSSPseudoClass.mozFullScreen },
                { ":-moz-full-screen-ancestor", nsCSSPseudoClass.mozFullScreenAncestor },
                { ":-moz-focusring", nsCSSPseudoClass.mozFocusRing },
                { ":-moz-broken", nsCSSPseudoClass.mozBroken },
                { ":-moz-user-disabled", nsCSSPseudoClass.mozUserDisabled },
                { ":-moz-suppressed", nsCSSPseudoClass.mozSuppressed },
                { ":-moz-loading", nsCSSPseudoClass.mozLoading },
                { ":-moz-type-unsupported", nsCSSPseudoClass.mozTypeUnsupported },
                { ":-moz-type-unsupported-platform", nsCSSPseudoClass.mozTypeUnsupportedPlatform },
                { ":-moz-handler-clicktoplay", nsCSSPseudoClass.mozHandlerClickToPlay },
                { ":-moz-handler-playpreview", nsCSSPseudoClass.mozHandlerPlayPreview },
                { ":-moz-handler-vulnerable-updatable", nsCSSPseudoClass.mozHandlerVulnerableUpdatable },
                { ":-moz-handler-vulnerable-no-update", nsCSSPseudoClass.mozHandlerVulnerableNoUpdate },
                { ":-moz-handler-disabled", nsCSSPseudoClass.mozHandlerDisabled },
                { ":-moz-handler-blocked", nsCSSPseudoClass.mozHandlerBlocked },
                { ":-moz-handler-crashed", nsCSSPseudoClass.mozHandlerCrashed },
                { ":-moz-math-increment-script-level", nsCSSPseudoClass.mozMathIncrementScriptLevel },
                { ":required", nsCSSPseudoClass.required },
                { ":optional", nsCSSPseudoClass.optional },
                { ":valid", nsCSSPseudoClass.valid },
                { ":invalid", nsCSSPseudoClass.invalid },
                { ":in-range", nsCSSPseudoClass.inRange },
                { ":out-of-range", nsCSSPseudoClass.outOfRange },
                { ":default", nsCSSPseudoClass.defaultPseudo },
                { ":-moz-read-only", nsCSSPseudoClass.mozReadOnly },
                { ":-moz-read-write", nsCSSPseudoClass.mozReadWrite },
                { ":-moz-submit-invalid", nsCSSPseudoClass.mozSubmitInvalid },
                { ":-moz-ui-invalid", nsCSSPseudoClass.mozUIInvalid },
                { ":-moz-ui-valid", nsCSSPseudoClass.mozUIValid },
                { ":-moz-meter-optimum", nsCSSPseudoClass.mozMeterOptimum },
                { ":-moz-meter-sub-optimum", nsCSSPseudoClass.mozMeterSubOptimum },
                { ":-moz-meter-sub-sub-optimum", nsCSSPseudoClass.mozMeterSubSubOptimum },
                { ":-moz-placeholder", nsCSSPseudoClass.mozPlaceholder },
            };
    }
}
