//
// Generated file. Do not edit manually.
//

using System.Collections.Generic;
using Alba.CsCss.Internal;

namespace Alba.CsCss.Style
{
    internal static partial class nsCSSPseudoClasses
    {
        private static readonly IDictionary<string, CssPseudoClass> sPseudoClasses =
            new Dictionary<string, CssPseudoClass>(ReferenceEqualityComparer<string>.Default) {
                { ":empty", CssPseudoClass.Empty },
                { ":-moz-only-whitespace", CssPseudoClass.MozOnlyWhitespace },
                { ":-moz-empty-except-children-with-localname", CssPseudoClass.MozEmptyExceptChildrenWithLocalname },
                { ":lang", CssPseudoClass.Lang },
                { ":-moz-bound-element", CssPseudoClass.MozBoundElement },
                { ":root", CssPseudoClass.Root },
                { ":-moz-any", CssPseudoClass.Any },
                { ":first-child", CssPseudoClass.FirstChild },
                { ":-moz-first-node", CssPseudoClass.FirstNode },
                { ":last-child", CssPseudoClass.LastChild },
                { ":-moz-last-node", CssPseudoClass.LastNode },
                { ":only-child", CssPseudoClass.OnlyChild },
                { ":first-of-type", CssPseudoClass.FirstOfType },
                { ":last-of-type", CssPseudoClass.LastOfType },
                { ":only-of-type", CssPseudoClass.OnlyOfType },
                { ":nth-child", CssPseudoClass.NthChild },
                { ":nth-last-child", CssPseudoClass.NthLastChild },
                { ":nth-of-type", CssPseudoClass.NthOfType },
                { ":nth-last-of-type", CssPseudoClass.NthLastOfType },
                { ":-moz-is-html", CssPseudoClass.MozIsHtml },
                { ":-moz-system-metric", CssPseudoClass.MozSystemMetric },
                { ":-moz-locale-dir", CssPseudoClass.MozLocaleDir },
                { ":-moz-lwtheme", CssPseudoClass.MozLwtheme },
                { ":-moz-lwtheme-brighttext", CssPseudoClass.MozLwthemeBrightText },
                { ":-moz-lwtheme-darktext", CssPseudoClass.MozLwthemeDarkText },
                { ":-moz-window-inactive", CssPseudoClass.MozWindowInactive },
                { ":-moz-table-border-nonzero", CssPseudoClass.MozTableBorderNonzero },
                { ":scope", CssPseudoClass.Scope },
                { ":not", CssPseudoClass.NotPseudo },
                { ":-moz-dir", CssPseudoClass.Dir },
                { ":link", CssPseudoClass.Link },
                { ":-moz-any-link", CssPseudoClass.MozAnyLink },
                { ":visited", CssPseudoClass.Visited },
                { ":active", CssPseudoClass.Active },
                { ":checked", CssPseudoClass.Checked },
                { ":disabled", CssPseudoClass.Disabled },
                { ":enabled", CssPseudoClass.Enabled },
                { ":focus", CssPseudoClass.Focus },
                { ":hover", CssPseudoClass.Hover },
                { ":-moz-drag-over", CssPseudoClass.MozDragOver },
                { ":target", CssPseudoClass.Target },
                { ":indeterminate", CssPseudoClass.Indeterminate },
                { ":-moz-full-screen", CssPseudoClass.MozFullScreen },
                { ":-moz-full-screen-ancestor", CssPseudoClass.MozFullScreenAncestor },
                { ":-moz-focusring", CssPseudoClass.MozFocusRing },
                { ":-moz-broken", CssPseudoClass.MozBroken },
                { ":-moz-user-disabled", CssPseudoClass.MozUserDisabled },
                { ":-moz-suppressed", CssPseudoClass.MozSuppressed },
                { ":-moz-loading", CssPseudoClass.MozLoading },
                { ":-moz-type-unsupported", CssPseudoClass.MozTypeUnsupported },
                { ":-moz-type-unsupported-platform", CssPseudoClass.MozTypeUnsupportedPlatform },
                { ":-moz-handler-clicktoplay", CssPseudoClass.MozHandlerClickToPlay },
                { ":-moz-handler-playpreview", CssPseudoClass.MozHandlerPlayPreview },
                { ":-moz-handler-vulnerable-updatable", CssPseudoClass.MozHandlerVulnerableUpdatable },
                { ":-moz-handler-vulnerable-no-update", CssPseudoClass.MozHandlerVulnerableNoUpdate },
                { ":-moz-handler-disabled", CssPseudoClass.MozHandlerDisabled },
                { ":-moz-handler-blocked", CssPseudoClass.MozHandlerBlocked },
                { ":-moz-handler-crashed", CssPseudoClass.MozHandlerCrashed },
                { ":-moz-math-increment-script-level", CssPseudoClass.MozMathIncrementScriptLevel },
                { ":required", CssPseudoClass.Required },
                { ":optional", CssPseudoClass.Optional },
                { ":valid", CssPseudoClass.Valid },
                { ":invalid", CssPseudoClass.Invalid },
                { ":in-range", CssPseudoClass.InRange },
                { ":out-of-range", CssPseudoClass.OutOfRange },
                { ":default", CssPseudoClass.DefaultPseudo },
                { ":-moz-read-only", CssPseudoClass.MozReadOnly },
                { ":-moz-read-write", CssPseudoClass.MozReadWrite },
                { ":-moz-submit-invalid", CssPseudoClass.MozSubmitInvalid },
                { ":-moz-ui-invalid", CssPseudoClass.MozUiinvalid },
                { ":-moz-ui-valid", CssPseudoClass.MozUivalid },
                { ":-moz-meter-optimum", CssPseudoClass.MozMeterOptimum },
                { ":-moz-meter-sub-optimum", CssPseudoClass.MozMeterSubOptimum },
                { ":-moz-meter-sub-sub-optimum", CssPseudoClass.MozMeterSubSubOptimum },
                { ":-moz-placeholder", CssPseudoClass.MozPlaceholder },
            };
    }
}
