//
// Generated file. Do not edit manually.
//

using System.Collections.Generic;
using Alba.CsCss.Internal;

namespace Alba.CsCss.Style
{
    internal static partial class nsCSSPseudoClasses
    {
        private static readonly IDictionary<string, CssPseudoClass> sPseudoClasses =
            new Dictionary<string, CssPseudoClass>(ReferenceEqualityComparer<object>.Default) {
                { ":empty", CssPseudoClass.empty },
                { ":-moz-only-whitespace", CssPseudoClass.mozOnlyWhitespace },
                { ":-moz-empty-except-children-with-localname", CssPseudoClass.mozEmptyExceptChildrenWithLocalname },
                { ":lang", CssPseudoClass.lang },
                { ":-moz-bound-element", CssPseudoClass.mozBoundElement },
                { ":root", CssPseudoClass.root },
                { ":-moz-any", CssPseudoClass.any },
                { ":first-child", CssPseudoClass.firstChild },
                { ":-moz-first-node", CssPseudoClass.firstNode },
                { ":last-child", CssPseudoClass.lastChild },
                { ":-moz-last-node", CssPseudoClass.lastNode },
                { ":only-child", CssPseudoClass.onlyChild },
                { ":first-of-type", CssPseudoClass.firstOfType },
                { ":last-of-type", CssPseudoClass.lastOfType },
                { ":only-of-type", CssPseudoClass.onlyOfType },
                { ":nth-child", CssPseudoClass.nthChild },
                { ":nth-last-child", CssPseudoClass.nthLastChild },
                { ":nth-of-type", CssPseudoClass.nthOfType },
                { ":nth-last-of-type", CssPseudoClass.nthLastOfType },
                { ":-moz-is-html", CssPseudoClass.mozIsHTML },
                { ":-moz-system-metric", CssPseudoClass.mozSystemMetric },
                { ":-moz-locale-dir", CssPseudoClass.mozLocaleDir },
                { ":-moz-lwtheme", CssPseudoClass.mozLWTheme },
                { ":-moz-lwtheme-brighttext", CssPseudoClass.mozLWThemeBrightText },
                { ":-moz-lwtheme-darktext", CssPseudoClass.mozLWThemeDarkText },
                { ":-moz-window-inactive", CssPseudoClass.mozWindowInactive },
                { ":-moz-table-border-nonzero", CssPseudoClass.mozTableBorderNonzero },
                { ":scope", CssPseudoClass.scope },
                { ":not", CssPseudoClass.notPseudo },
                { ":-moz-dir", CssPseudoClass.dir },
                { ":link", CssPseudoClass.link },
                { ":-moz-any-link", CssPseudoClass.mozAnyLink },
                { ":visited", CssPseudoClass.visited },
                { ":active", CssPseudoClass.active },
                { ":checked", CssPseudoClass.@checked },
                { ":disabled", CssPseudoClass.disabled },
                { ":enabled", CssPseudoClass.enabled },
                { ":focus", CssPseudoClass.focus },
                { ":hover", CssPseudoClass.hover },
                { ":-moz-drag-over", CssPseudoClass.mozDragOver },
                { ":target", CssPseudoClass.target },
                { ":indeterminate", CssPseudoClass.indeterminate },
                { ":-moz-full-screen", CssPseudoClass.mozFullScreen },
                { ":-moz-full-screen-ancestor", CssPseudoClass.mozFullScreenAncestor },
                { ":-moz-focusring", CssPseudoClass.mozFocusRing },
                { ":-moz-broken", CssPseudoClass.mozBroken },
                { ":-moz-user-disabled", CssPseudoClass.mozUserDisabled },
                { ":-moz-suppressed", CssPseudoClass.mozSuppressed },
                { ":-moz-loading", CssPseudoClass.mozLoading },
                { ":-moz-type-unsupported", CssPseudoClass.mozTypeUnsupported },
                { ":-moz-type-unsupported-platform", CssPseudoClass.mozTypeUnsupportedPlatform },
                { ":-moz-handler-clicktoplay", CssPseudoClass.mozHandlerClickToPlay },
                { ":-moz-handler-playpreview", CssPseudoClass.mozHandlerPlayPreview },
                { ":-moz-handler-vulnerable-updatable", CssPseudoClass.mozHandlerVulnerableUpdatable },
                { ":-moz-handler-vulnerable-no-update", CssPseudoClass.mozHandlerVulnerableNoUpdate },
                { ":-moz-handler-disabled", CssPseudoClass.mozHandlerDisabled },
                { ":-moz-handler-blocked", CssPseudoClass.mozHandlerBlocked },
                { ":-moz-handler-crashed", CssPseudoClass.mozHandlerCrashed },
                { ":-moz-math-increment-script-level", CssPseudoClass.mozMathIncrementScriptLevel },
                { ":required", CssPseudoClass.required },
                { ":optional", CssPseudoClass.optional },
                { ":valid", CssPseudoClass.valid },
                { ":invalid", CssPseudoClass.invalid },
                { ":in-range", CssPseudoClass.inRange },
                { ":out-of-range", CssPseudoClass.outOfRange },
                { ":default", CssPseudoClass.defaultPseudo },
                { ":-moz-read-only", CssPseudoClass.mozReadOnly },
                { ":-moz-read-write", CssPseudoClass.mozReadWrite },
                { ":-moz-submit-invalid", CssPseudoClass.mozSubmitInvalid },
                { ":-moz-ui-invalid", CssPseudoClass.mozUIInvalid },
                { ":-moz-ui-valid", CssPseudoClass.mozUIValid },
                { ":-moz-meter-optimum", CssPseudoClass.mozMeterOptimum },
                { ":-moz-meter-sub-optimum", CssPseudoClass.mozMeterSubOptimum },
                { ":-moz-meter-sub-sub-optimum", CssPseudoClass.mozMeterSubSubOptimum },
                { ":-moz-placeholder", CssPseudoClass.mozPlaceholder },
            };
    }
}
